dist: trusty
sudo: required
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
os:
- linux
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
before_install:
- echo "$TRAVIS_BRANCH"
- echo "$TRAVIS_PULL_REQUEST"
- export CHROME_BIN=chromium-browser
install:
- npm install
script:
- npm run build
env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="dist"
    - TARGET_BRANCH="gh-pages"
    - GIT_EMAIL="nguyenthanhvy105@gmail.com"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "60607e4e9fcf3a2a662ba4b7e2a30a3b5b71a60b"
  keep-history: true
  on:
    branch: master
