dist: trusty
sudo: required
language: node_js
node_js:
- '9'
- '10'
cache:
  directories:
  - node_modules
os:
- linux
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
before_install:
- export CHROME_BIN=chromium-browser
install:
- yarn install
script:
- yarn run build
env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="dist"
    - GIT_EMAIL="nguyenthanhvy105@gmail.com"
