dist: trusty
sudo: required
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
os:
- linux
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
before_install:
- export CHROME_BIN=chromium-browser
install:
- npm install -g yarn
- yarn install
script:
- yarn run build
env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="dist"
    - TARGET_BRANCH="gh-pages"
    - GIT_EMAIL="nguyenthanhvy105@gmail.com"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: dist/ng/examples
  on:
    branch: master
